# Generated by Django 4.1.7 on 2023-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='present',
        ),
        migrations.AddField(
            model_name='attendance',
            name='department',
            field=models.CharField(max_length=100, null='NA'),
            preserve_default='NA',
        ),
        migrations.AddField(
            model_name='attendance',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faces',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
